AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 128
    Timeout: 15
Resources:
  AllowS3ToCallLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: S3TriggeredLambdaHandler
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - S3Bucket
        - Arn
  S3TriggeredLambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://demo-lambda-deploy/6b59a3e083549974be4011f9c52f47eb
      Handler: lambda.handler
      Description: Function that is called when a file is stored in S3.
      Runtime: nodejs12.x
      Events:
        S3Bucket:
          Type: S3
          Properties:
            Bucket:
              Ref: S3Bucket
            Events: s3:ObjectCreated:*
  S3Bucket:
    Type: AWS::S3::Bucket
